version: '3.8'

services:
  valkey:
    image: valkey/valkey:7-alpine
    container_name: streampulse-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  valkey_data: 